### ISSUE TITLE
following moodle branches naming convention

### ISSUE THREAD

**Issue by pfautrero** [justinhunt/moodle-filter_poodll#13]
Hi Justin,

Is it possible for all poodll extensions to follow moodle branches names ? In my case, I have to deploy moodle in an automatic way and scripts checkout all plugins used each time we want to upgrade. It could be really nice if MOODLE_29_STABLE, MOODLE_30_STABLE and MOODLE_31_STABLE branches exist in your different repos.

Thanks

**Comment by justinhunt** [comment]
Thanks for the comment. We did go astray with our naming, I think thats true. We won't be releasing a different branch for each branch of Moodle. But in future we will try and at least match the minimum Moodle version in the way your suggest.
