### ISSUE TITLE
Unable to use DrawingBoard - JS Errors (Poodll 3)

### ISSUE THREAD

**Issue by nadavkav** [justinhunt/moodle-filter_poodll#18]
![image](https://cloud.githubusercontent.com/assets/231168/19124710/ee98cbca-8b3c-11e6-9c20-c711ab4935bd.png)

**Comment by nadavkav** [comment]
drawingboard.min.js:1 Uncaught ReferenceError: $ is not definedDrawingBoard.Control.extend @ drawingboard.min.js:1(anonymous function) @ drawingboard.min.js:1
content.min.js:1 XHR finished loading: GET "chrome-extension://mgijmajocgfcbeboacabfgobmjgjcoja/content.min.css".u @ content.min.js:1y @ content.min.js:1(anonymous function) @ content.min.js:18(anonymous function) @ content.min.js:18
drawingboard.min.js:1 Uncaught TypeError: Cannot read property 'extend' of undefinedDrawingBoard.Board @ drawingboard.min.js:1loaddrawingboard @ module.js:1(anonymous function) @ preview.php?id=273452&courseid=126:245_notify @ yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js&rollup/1475689545/mcore-min.js:9T @ yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js&rollup/1475689545/mcore-min.js:9_finish @ yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js&rollup/1475689545/mcore-min.js:16_onSuccess @ yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js&rollup/1475689545/mcore-min.js:16p @ yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js&rollup/1475689545/mcore-min.js:17onSuccess @ yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js&rollup/1475689545/mcore-min.js:17_finish @ yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js&rollup/1475689545/mcore-min.js:12_next @ yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js&rollup/1475689545/mcore-min.js:12_progress @ yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js&rollup/1475689545/mcore-min.js:13h @ yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js&rollup/1475689545/mcore-min.js:12

**Comment by nadavkav** [comment]
I am getting this only in poodll questions and not in Atto editor (poodll buttons)
Seems like jquery is not recognised (although loaded)

**Comment by nadavkav** [comment]
This has started to happen after upgrading from M29 Poodll version to M31 Poodll 3 (paid) version.

**Comment by nadavkav** [comment]
Hi @justinhunt , Please see if you can give us some insight to what is causing it so maybe we could fix it ourselves.

**Comment by justinhunt** [comment]
Sorry Nadav, I have been back in New Zealand at a conference and visiting family,  or I would have gotten onto this earlier. I will check later today and see whats up.

**Comment by nadavkav** [comment]
Bless you :smile:  
(Wish I could be on the New Zealand MOOT or the Australian one too, one day...)

**Comment by justinhunt** [comment]
Nadav, I just uploaded a branch that should address this. In the end I implemented a "shim" for drawingboard.js so that it can be used with AMD. Thanks for the report.

**Comment by nadavkav** [comment]
Solved :smile: Bless you!
