### ISSUE TITLE
Confusing buttons in recorder

### ISSUE THREAD

**Issue by psvec** [justinhunt/moodle-filter_poodll#19]
In the recorder (in the submission) there is a confusing button "Save". It would be better to rename it to "Upload". The reason is that there is another button "Save changes" in the submission.

The language string is **filter_poodll -> recui_save** 

I renamed it my local installation to "Upload audio/video to the system"

![poodle-confuse](https://cloud.githubusercontent.com/assets/8381906/20087662/8f18f1be-a5b5-11e6-8836-19a547f6a881.png)

**Comment by justinhunt** [comment]
That is a good observation. You stop seeing these things after a while. I
will do that on the next release.
Thanks for letting me know.

**Comment by justinhunt** [comment]
In the latest release of PoodLL this is done. (branch poodll3)
