### ISSUE TITLE
ResponsiveIFrame js keeps increasing the poodll dialog height

### ISSUE THREAD

**Issue by nadavkav** [justinhunt/moodle-filter_poodll#20]
We just recently noticed that responsiveiframe.js keeps increasing the poodll dialog height
immediately after any of the poodll buttons is clicked and the respective poodll dialog is displayed.
I have not changed the browser's window size, it just happens, endlessly, on its own.
I must imagine we are the only ones getting this, as it prevent the users from being able to work at all.

**Comment by nadavkav** [comment]
@hannaedelman , that might interest you too

**Comment by justinhunt** [comment]
HI Nadav. I did not notice this. It might be theme specific. Does it also happen it https://demo.poodll.com?
What theme are you using?

**Comment by nadavkav** [comment]
We are using a customized Essential theme. I just noticed it a day ago, and though one of our team upgraded it from your git repo. but I guess it was not upgraded. and the cause for it is somewhere else on our system.

**Comment by nadavkav** [comment]
It's not happening on demo.poodll.com

**Comment by nadavkav** [comment]
Thanks
