### ISSUE TITLE
Undefined constant AWS_NONE throwing error on upgrade

### ISSUE THREAD

**Issue by logan-reynolds** [justinhunt/moodle-filter_poodll#34]
The following error is happening with the latest version 2020061400 release 3.1.34 (Build 2020061400) of filter_poodll when attempting upgrade from the previous version, which leaves the site stuck at the plugin upgrade screen:
```
!!! Exception - Undefined class constant 'AWS_NONE' !!!
!!
Error code: generalexceptionmessage !!
!! Stack trace: * line 97 of /filter/poodll/db/upgrade.php: Error thrown
    line 632 of /lib/upgradelib.php: call to xmldb_filter_poodll_upgrade()
    line 1857 of /lib/upgradelib.php: call to upgrade_plugins()
    line 182 of /admin/cli/upgrade.php: call to upgrade_noncore()
    !!
```

**Comment by justinhunt** [comment]
Thanks for this, that was a good catch. I appreciate it. Please try again and let me know if you run into more problems
