### ISSUE TITLE
unsafe variable value setting

### ISSUE THREAD

**Issue by ndunand** [justinhunt/moodle-filter_poodll#4]
in https://github.com/justinhunt/moodle-filter_poodll/blob/master/poodllresourcelib.php#L3434 , raw values are set for params, which does not work in French, as

    filter_poodll.php:$string['recui_echo'] = 'Suppression d\'écho';

contains an apostrophe, which is considered a string delimiter in JS. Therefore, running the code as-is results in a JS error, and no recorder is displayer.

I've replaced `$value` by `urlencode($value)` in the above mentioned place in the code, and it seems to fix the problem.

**Comment by justinhunt** [comment]
Thanks for the report. And you are right it should be surrounded by
urlencode() when it is used in a url.

In function filter_poodll_fetch_recorder_strings()
https://github.com/justinhunt/moodle-filter_poodll/blob/master/poodllresourcelib.php#L3040
I use urlencode. I thought that was the only place I used those lang
strings.

I believe that you did have this problem though. I am wondering if you
could tell me where it occurred?

Justin

**Comment by ndunand** [comment]
You are right. My bad for using an outdated version of the plugin. Sorry for the bother.

**Comment by justinhunt** [comment]
No problem it all. I appreciate you looking at it and letting me know. The
exceptionally odd thing is that yesterday I also received a report of the
the same mistake on another plugin. And it was a similar accented French
string that broke it. In that case it was a bug I had to fix.
