### ISSUE TITLE
Fatal Error in Moodle 2.9

### ISSUE THREAD

**Issue by fernandooliveira** [justinhunt/moodle-filter_poodll#6]
After a number of tests, this plugin was rejected by our Moodle hosting provider for the following reasons:

The filter does not display the Whiteboard recorder due to Javascript not fully loading jquery before running.

The following fatal error is encountered:
TypeError: $ is undefined in drawingboard.min.js

Furthermore, the plugin does not seem to adhere to M29's standards for AMD style javascript.

**Comment by justinhunt** [comment]
That is correct. The javascript whiteboards are broken in PoodLL and Moodle 2.9. They will be fixed in PoodLL 3.0.  There is still no ETA on that unfortunately. But its a month or two, not a year or two.

**Comment by justinhunt** [comment]
In PoodLL3 all the whiteboards are now working under AMD. So I am closing this.
