### ISSUE TITLE
HTML5 audio recorder doesn't appear

### ISSUE THREAD

**Issue by gabrielrosset** [justinhunt/moodle-filter_poodll#8]
While "always use HTML5" is selected for the recorder into the filter settings the audio recorder doesn't appear anywhere, there's juste a button "record or choose a file".
When clicked this button only allows to choose an audio file in the client file system.

There is no problem when the flash recorder is activated, it takes place instead of the previously mentionned button and works well.

Test context : 
Moodle 2.9.3+ (test site only available into a local network)
All latest version from poodll plugins set installed (poodll filter : version 2.8.3(Build 2015121104))

**Comment by justinhunt** [comment]
Thanks for the report. In fact this is the correct behaviour. We do not yet have a better html5 recording methid than file upload. This works ok on mobile because in most cases they will have the option there to directly record a file from the device there.
